### ISSUE TITLE
Demo script does not work

### ISSUE THREAD

**Issue by antoinecarme** [antoinecarme/sklearn2sql_heroku#1]
The sample script given of the main page does not work.

Output : 
```
python ./tests/demo.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

travis-ci logs are also failing : 

https://travis-ci.org/antoinecarme/sklearn2sql_heroku

![image](https://user-images.githubusercontent.com/16481992/32728258-e37390fa-c87f-11e7-8e13-49a506a96116.png)

**Comment by antoinecarme** [comment]
FIXED the backend.
